### ISSUE TITLE
WORK SCHEDULE

### ISSUE THREAD

**Issue by ROBOTIS-Leon** [ROBOTIS-GIT/DynamixelSDK#17]
## Future works
- [ ] (Recover) Check if the id of rxpacket is the same as the id of txpacket #82 
- [ ] DynamixelSDK Python - fully pythonize #93 #122 #147

 
## Postponed
- [ ] DynamixelSDK test on Windows 10 IoT Core #7 
- [ ] Example codes that run by getting input values (goal positions, led values, etc.)
- [ ] Symlinks issue #89 

- [ ] Some works for USB2AX #106
- [ ] Arbotix-M controller test #30 

### v3.5.4
- Fixes : Error compiling SDK on Mac OSX: "use of undeclared identifier 'CLOCK_REALTIME'" #141 #144
- Fixes : Truncated packet transmission on OSX #142 #143
- Fixes : weird performance of 'Read' between Ubuntu 14.04 and Ubuntu 16.04 #146 

### v3.5.3
- Fixes : DynamixelSDK ROS Kinetic Issue - ARM - Debian Jessie solved by replacing target_sources func in CMake to set_property #136

### v3.5.2
- Recover : Check if the id of rxpacket is the same as the id of txpacket (c++) #82
- Changes : Ping examples now will not show Dynamixel model number when communication is failed

### v3.5.1
- DynamixelSDK for MacOSX #51 
- DynamixelSDK for Arduino #11 #34

### v3.4.3
- DynamixelSDK C++ ver. and ROS ver. in Windows platform now can use the port number of over then 10 #45

### v3.4.2
- MATLAB loadlibrary error #34  #36 

### v3.4.1
- some modification in the ROS .xml file

### v3.4.0
- ROS enabled

### v3.3.3
- Makefile in C & C++ ver. SDK : Makefile for SBCs upload
-  [MATLAB example - platform auto-detection](https://github.com/ROBOTIS-GIT/DynamixelSDK/issues/1)
-  Byte combination functions in `packet_handler.h` to be visible

**Comment by ROBOTIS-Leon** [comment]
We are working on the OpenCR, which is a board that can work with ROS Serial or Arduino between SBC (or Computer) and the Dynamixel now, and the DynamixelSDK 3.X for Arduino as a library file has been uploaded from few weeks ago. 

If you have interested with your Arduino x Dynamixel issue, come [here](https://github.com/ROBOTIS-GIT/OpenCR/tree/master/arduino/opencr_arduino/opencr/libraries) and get the temporary source.

The official library files (or package that is available through the Arduino IDE update, maybe) would be serviced soon.
